.TH PEEK 1 "September 2013"
.SH NAME
peek - The simple cheatsheet handler
.SH SYNOPSIS
peek [ -h ][ -l ][ -e file ][ file ]
.SH DESCRIPTION
peek is a simple cheatsheet handler. You can use it for your daily system
administration tasks, to read some notes, to take a peek out of your favourite
one-liners or anything else that you use often but not so often to remember. If
no option is passed to peek but a filename, peek searches in the CHEATSHEET_DIR
to open it. See peek.h if you want to set it to another directory. If the
cheatsheet does not exist, peek informs the user with an error. If the file has
a lot of lines, a pager like less(1) can be used to ease your tasks. No back up
function exist, since the text editor should handle your backups. An editor like
mg or vim should work like a charm. See Examples.
.SS OPTIONS
.TP
-h
Show the help message and exit.
.TP
-l
List all available cheatsheets.
.TP
-e
Create or open a cheatsheet with your editor.
.SH FILES
.TP
CHEATSHEET_DIR:
The directory that your cheatsheets are saved.
By default, this is ~/.peek/ . If you want to
change it edit the "peek.h" file.
.SH "EXAMPLES"
1. Open the tar cheatsheet and then exit succesfully:

peek tar or peek tar | less

2. Open existing tar cheatsheet and when
done exit succesfully:

peek -e tar

3. List all existing cheatsheets and then exit:

peek -l

.SH BUGS
Probably A LOT. Please report any bugs or hit me a /msg
on irc: dwts@freenode or join #2f30 @freenode.
.SH REPO
The latest version of peek can be found on this link:

https://github.com/s-p-k/peek

.SH COPYRIGHT
Copyright (c) 2013, spk (vizard.sepuku@gmail.com)
